### ISSUE TITLE
大神你的demo不知道怎么测试登陆

### ISSUE THREAD

**Issue by MyPrivateAccount** [CavinCao/NetCoreDemo#1]
请教一下，这个demo测试运行时怎么进行第一次登陆，是不是需要仔细构造token或者cookie放到请求中，还有就是   if (path.StartsWith("/swagger") || excludeUrl.Contains(path))一句excludeUrl.Contains(path)是想在下一个中间件进行一些什么样的操作，还有就是我怎么能获取到二维码，以及为什么启动demo时会自动跳到http://localhost:31075/api/values,希望大神能给予指点，多谢了！

**Comment by CavinCao** [comment]
这个只是后端服务，具体的登录操作要配合前端进行
api/values跳转到这个，是因为设置的初始页面
如果过有什么问题可以加我微信，wuxinxiake123
